[[plugins]]
repo = 'Shougo/cmdline.vim'
#on_source = ['ddu.vim']
#hook_add = '''
#  cnoremap <CR>  <Cmd>call cmdline#disable()<CR><CR>
#'''
#hook_source = '''
#  call cmdline#set_option(#{
#    \   highlight_window: 'None',
#    \ })
#'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'BufNewFile']
on_cmd = ['TSInstall', 'TSUpdate']
rev = 'main'
hooks_file = '$BASE_DIR/hooks/treesitter.lua'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'mason-org/mason.nvim'
depends = ['nvim-lspconfig']
lua_source = '''
  require("mason").setup()
'''

[[plugins]]
repo = 'mason-org/mason-lspconfig.nvim'
depends = ['mason.nvim', 'nvim-lspconfig']
on_event = ['BufReadPre', 'BufNewFile' ]
lua_source = '''
  local ensure_installed = {
    "lua_ls",
    "denols",
  }
  require("mason-lspconfig").setup({
    ensure_installed = ensure_installed,
  })

  require("core.lsp")
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc.vim'
hook_source = '''
call signature_help#enable()
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''
